name: Build LogUtil (Windows + macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: Test\build.bat
        shell: cmd

      - name: Make build.sh executable (macOS)
        if: runner.os == 'macOS'
        run: chmod +x Test/build.sh

      - name: Build on macOS
        if: runner.os == 'macOS'
        run: ./Test/build.sh
        shell: bash
